### ISSUE TITLE
Using plugin within a docker

### ISSUE THREAD

**Issue by ceraz68** [willyzha/homebridge-wifi-home-sensor#3]
I tried to use this plugin on a docker on Synology. The arp-scan command is not supported. I tried editing the index.js file to replace the exec command with "arp -i bond0 | grep -i" + this.mac without success.

I checked that the exec command works on the docker via ssh using commands like "sudo docker exec -it homebridge sudo arp -i bond0"

Any hints ?
Thanks

**Comment by maxime-killinger** [comment]
Hi,
Just got the same problem here. Run `ip a` on your docker, and look for the interface that have your local address, it's "br0". So the command will be `sudo arp-scan --interface="br0" -l`

**Comment by ceraz68** [comment]
In the end I decided to make my own plugin. Synology docker has limited arp functionality. I use exec to launch the below combination with awk, helped me to build a file containing an ip+mac address per line.

`"arp -a | awk '{gsub(/[()]/,\"\"); print $2\",\"$4}' > arpFile.csv"`

Then easy to convert to an array and play around with the data
